// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortLinkService.Web.Entities;

namespace ShortLinkService.Web.Migrations
{
    [DbContext(typeof(ShortLinkServiceDbContext))]
    partial class ShortLinkServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShortLinkService.Web.Entities.LinkAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BitmapCodePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullLink")
                        .HasColumnType("nvarchar(416)")
                        .HasMaxLength(416);

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(26)")
                        .HasMaxLength(26);

                    b.HasKey("Id");

                    b.ToTable("LinkAliases");
                });
#pragma warning restore 612, 618
        }
    }
}
